[font]
normal.family = "SauceCodePro Nerd Font Mono"
bold.family = "SauceCodePro Nerd Font Mono"
italic.family = "SauceCodePro Nerd Font Mono"
bold_italic.family = "SauceCodePro Nerd Font Mono"

size = 14.0

[window]
opacity = 0.8
blur = true
dimensions = {columns = 150, lines = 40}

decorations_theme_variant = "Dark"

[selection]
save_to_clipboard = true

[cursor]
# style = {shape = "Beam", blinking = "Never"}

